apiVersion: v1
kind: ConfigMap
metadata:
  name: template-single-configmap
data:
  config.yaml: |
    server:
      address:     ":8000"
      openapiPath: "/api.json"
      swaggerPath: "/swagger"

    logger:
      level : "all"
      stdout: true

    crypto:
      encryptionKey: ""  # 必填：运行 openssl rand -hex 32 生成，与其他环境隔离
