// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// apiKeysDao is the data access object for the table api_keys.
// You can define custom methods on it to extend its functionality as needed.
type apiKeysDao struct {
	*internal.ApiKeysDao
}

var (
	// ApiKeys is a globally accessible object for table api_keys operations.
	ApiKeys = apiKeysDao{internal.NewApiKeysDao()}
)

// Add your custom methods and functionality below.
