// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// apiKeyModelScopesDao is the data access object for the table api_key_model_scopes.
// You can define custom methods on it to extend its functionality as needed.
type apiKeyModelScopesDao struct {
	*internal.ApiKeyModelScopesDao
}

var (
	// ApiKeyModelScopes is a globally accessible object for table api_key_model_scopes operations.
	ApiKeyModelScopes = apiKeyModelScopesDao{internal.NewApiKeyModelScopesDao()}
)

// Add your custom methods and functionality below.
