// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// internalAudLoginHistoryDao is an internal type for wrapping the internal DAO implementation.
type internalAudLoginHistoryDao = *internal.AudLoginHistoryDao

// audLoginHistoryDao is the data access object for the table aud_login_history.
// You can define custom methods on it to extend its functionality as needed.
type audLoginHistoryDao struct {
	internalAudLoginHistoryDao
}

var (
	// AudLoginHistory is a globally accessible object for table aud_login_history operations.
	AudLoginHistory = audLoginHistoryDao{
		internal.NewAudLoginHistoryDao(),
	}
)

// Add your custom methods and functionality below.
