// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// audContentFilterLogsDao is the data access object for the table aud_content_filter_logs.
// You can define custom methods on it to extend its functionality as needed.
type audContentFilterLogsDao struct {
	*internal.AudContentFilterLogsDao
}

var (
	// AudContentFilterLogs is a globally accessible object for table aud_content_filter_logs operations.
	AudContentFilterLogs = audContentFilterLogsDao{internal.NewAudContentFilterLogsDao()}
)

// Add your custom methods and functionality below.
