// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// audOperationLogsDao is the data access object for the table aud_operation_logs.
// You can define custom methods on it to extend its functionality as needed.
type audOperationLogsDao struct {
	*internal.AudOperationLogsDao
}

var (
	// AudOperationLogs is a globally accessible object for table aud_operation_logs operations.
	AudOperationLogs = audOperationLogsDao{internal.NewAudOperationLogsDao()}
)

// Add your custom methods and functionality below.
