// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// audSensitiveAccessLogsDao is the data access object for the table aud_sensitive_access_logs.
// You can define custom methods on it to extend its functionality as needed.
type audSensitiveAccessLogsDao struct {
	*internal.AudSensitiveAccessLogsDao
}

var (
	// AudSensitiveAccessLogs is a globally accessible object for table aud_sensitive_access_logs operations.
	AudSensitiveAccessLogs = audSensitiveAccessLogsDao{internal.NewAudSensitiveAccessLogsDao()}
)

// Add your custom methods and functionality below.
