// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// audRequestLogsDao is the data access object for the table aud_request_logs.
// You can define custom methods on it to extend its functionality as needed.
type audRequestLogsDao struct {
	*internal.AudRequestLogsDao
}

var (
	// AudRequestLogs is a globally accessible object for table aud_request_logs operations.
	AudRequestLogs = audRequestLogsDao{internal.NewAudRequestLogsDao()}
)

// Add your custom methods and functionality below.
