// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilMonthlyRevenueSummaryDao is the data access object for the table bil_monthly_revenue_summary.
// You can define custom methods on it to extend its functionality as needed.
type bilMonthlyRevenueSummaryDao struct {
	*internal.BilMonthlyRevenueSummaryDao
}

var (
	// BilMonthlyRevenueSummary is a globally accessible object for table bil_monthly_revenue_summary operations.
	BilMonthlyRevenueSummary = bilMonthlyRevenueSummaryDao{internal.NewBilMonthlyRevenueSummaryDao()}
)

// Add your custom methods and functionality below.
