// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilWalletsDao is the data access object for the table bil_wallets.
// You can define custom methods on it to extend its functionality as needed.
type bilWalletsDao struct {
	*internal.BilWalletsDao
}

var (
	// BilWallets is a globally accessible object for table bil_wallets operations.
	BilWallets = bilWalletsDao{internal.NewBilWalletsDao()}
)

// Add your custom methods and functionality below.
