// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilUsageDailyDao is the data access object for the table bil_usage_daily.
// You can define custom methods on it to extend its functionality as needed.
type bilUsageDailyDao struct {
	*internal.BilUsageDailyDao
}

var (
	// BilUsageDaily is a globally accessible object for table bil_usage_daily operations.
	BilUsageDaily = bilUsageDailyDao{internal.NewBilUsageDailyDao()}
)

// Add your custom methods and functionality below.
