// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilMonthlyUsageSummaryDao is the data access object for the table bil_monthly_usage_summary.
// You can define custom methods on it to extend its functionality as needed.
type bilMonthlyUsageSummaryDao struct {
	*internal.BilMonthlyUsageSummaryDao
}

var (
	// BilMonthlyUsageSummary is a globally accessible object for table bil_monthly_usage_summary operations.
	BilMonthlyUsageSummary = bilMonthlyUsageSummaryDao{internal.NewBilMonthlyUsageSummaryDao()}
)

// Add your custom methods and functionality below.
