// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilPredeductTracksDao is the data access object for the table bil_prededuct_tracks.
// You can define custom methods on it to extend its functionality as needed.
type bilPredeductTracksDao struct {
	*internal.BilPredeductTracksDao
}

var (
	// BilPredeductTracks is a globally accessible object for table bil_prededuct_tracks operations.
	BilPredeductTracks = bilPredeductTracksDao{internal.NewBilPredeductTracksDao()}
)

// Add your custom methods and functionality below.
