// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilDailyRevenueSummaryDao is the data access object for the table bil_daily_revenue_summary.
// You can define custom methods on it to extend its functionality as needed.
type bilDailyRevenueSummaryDao struct {
	*internal.BilDailyRevenueSummaryDao
}

var (
	// BilDailyRevenueSummary is a globally accessible object for table bil_daily_revenue_summary operations.
	BilDailyRevenueSummary = bilDailyRevenueSummaryDao{internal.NewBilDailyRevenueSummaryDao()}
)

// Add your custom methods and functionality below.
