// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilDailyUsageSummaryDao is the data access object for the table bil_daily_usage_summary.
// You can define custom methods on it to extend its functionality as needed.
type bilDailyUsageSummaryDao struct {
	*internal.BilDailyUsageSummaryDao
}

var (
	// BilDailyUsageSummary is a globally accessible object for table bil_daily_usage_summary operations.
	BilDailyUsageSummary = bilDailyUsageSummaryDao{internal.NewBilDailyUsageSummaryDao()}
)

// Add your custom methods and functionality below.
