// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilRecordsDao is the data access object for the table bil_records.
// You can define custom methods on it to extend its functionality as needed.
type bilRecordsDao struct {
	*internal.BilRecordsDao
}

var (
	// BilRecords is a globally accessible object for table bil_records operations.
	BilRecords = bilRecordsDao{internal.NewBilRecordsDao()}
)

// Add your custom methods and functionality below.
