// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilUsageLogsDao is the data access object for the table bil_usage_logs.
// You can define custom methods on it to extend its functionality as needed.
type bilUsageLogsDao struct {
	*internal.BilUsageLogsDao
}

var (
	// BilUsageLogs is a globally accessible object for table bil_usage_logs operations.
	BilUsageLogs = bilUsageLogsDao{internal.NewBilUsageLogsDao()}
)

// Add your custom methods and functionality below.
