// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// bilTransactionsDao is the data access object for the table bil_transactions.
// You can define custom methods on it to extend its functionality as needed.
type bilTransactionsDao struct {
	*internal.BilTransactionsDao
}

var (
	// BilTransactions is a globally accessible object for table bil_transactions operations.
	BilTransactions = bilTransactionsDao{internal.NewBilTransactionsDao()}
)

// Add your custom methods and functionality below.
