// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnHealthScoresDao is the data access object for the table chn_health_scores.
// You can define custom methods on it to extend its functionality as needed.
type chnHealthScoresDao struct {
	*internal.ChnHealthScoresDao
}

var (
	// ChnHealthScores is a globally accessible object for table chn_health_scores operations.
	ChnHealthScores = chnHealthScoresDao{internal.NewChnHealthScoresDao()}
)

// Add your custom methods and functionality below.
