// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnChannelAffinitiesDao is the data access object for the table chn_channel_affinities.
// You can define custom methods on it to extend its functionality as needed.
type chnChannelAffinitiesDao struct {
	*internal.ChnChannelAffinitiesDao
}

var (
	// ChnChannelAffinities is a globally accessible object for table chn_channel_affinities operations.
	ChnChannelAffinities = chnChannelAffinitiesDao{internal.NewChnChannelAffinitiesDao()}
)

// Add your custom methods and functionality below.
