// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnErrorEventsDao is the data access object for the table chn_error_events.
// You can define custom methods on it to extend its functionality as needed.
type chnErrorEventsDao struct {
	*internal.ChnErrorEventsDao
}

var (
	// ChnErrorEvents is a globally accessible object for table chn_error_events operations.
	ChnErrorEvents = chnErrorEventsDao{internal.NewChnErrorEventsDao()}
)

// Add your custom methods and functionality below.
