// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnDebugLogsDao is the data access object for the table chn_debug_logs.
// You can define custom methods on it to extend its functionality as needed.
type chnDebugLogsDao struct {
	*internal.ChnDebugLogsDao
}

var (
	// ChnDebugLogs is a globally accessible object for table chn_debug_logs operations.
	ChnDebugLogs = chnDebugLogsDao{internal.NewChnDebugLogsDao()}
)

// Add your custom methods and functionality below.
