// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnChannelKeysDao is the data access object for the table chn_channel_keys.
// You can define custom methods on it to extend its functionality as needed.
type chnChannelKeysDao struct {
	*internal.ChnChannelKeysDao
}

var (
	// ChnChannelKeys is a globally accessible object for table chn_channel_keys operations.
	ChnChannelKeys = chnChannelKeysDao{internal.NewChnChannelKeysDao()}
)

// Add your custom methods and functionality below.
