// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnHealthSnapshotsDao is the data access object for the table chn_health_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type chnHealthSnapshotsDao struct {
	*internal.ChnHealthSnapshotsDao
}

var (
	// ChnHealthSnapshots is a globally accessible object for table chn_health_snapshots operations.
	ChnHealthSnapshots = chnHealthSnapshotsDao{internal.NewChnHealthSnapshotsDao()}
)

// Add your custom methods and functionality below.
