// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnChannelsDao is the data access object for the table chn_channels.
// You can define custom methods on it to extend its functionality as needed.
type chnChannelsDao struct {
	*internal.ChnChannelsDao
}

var (
	// ChnChannels is a globally accessible object for table chn_channels operations.
	ChnChannels = chnChannelsDao{internal.NewChnChannelsDao()}
)

// Add your custom methods and functionality below.
