// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// chnAbilitiesDao is the data access object for the table chn_abilities.
// You can define custom methods on it to extend its functionality as needed.
type chnAbilitiesDao struct {
	*internal.ChnAbilitiesDao
}

var (
	// ChnAbilities is a globally accessible object for table chn_abilities operations.
	ChnAbilities = chnAbilitiesDao{internal.NewChnAbilitiesDao()}
)

// Add your custom methods and functionality below.
