// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// clgChangelogsDao is the data access object for the table clg_changelogs.
// You can define custom methods on it to extend its functionality as needed.
type clgChangelogsDao struct {
	*internal.ClgChangelogsDao
}

var (
	// ClgChangelogs is a globally accessible object for table clg_changelogs operations.
	ClgChangelogs = clgChangelogsDao{internal.NewClgChangelogsDao()}
)

// Add your custom methods and functionality below.
