// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// filFilesDao is the data access object for the table fil_files.
// You can define custom methods on it to extend its functionality as needed.
type filFilesDao struct {
	*internal.FilFilesDao
}

var (
	// FilFiles is a globally accessible object for table fil_files operations.
	FilFiles = filFilesDao{internal.NewFilFilesDao()}
)

// Add your custom methods and functionality below.
