// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// gooseDbVersionDao is the data access object for the table goose_db_version.
// You can define custom methods on it to extend its functionality as needed.
type gooseDbVersionDao struct {
	*internal.GooseDbVersionDao
}

var (
	// GooseDbVersion is a globally accessible object for table goose_db_version operations.
	GooseDbVersion = gooseDbVersionDao{internal.NewGooseDbVersionDao()}
)

// Add your custom methods and functionality below.
