// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlModelsDao is the data access object for the table mdl_models.
// You can define custom methods on it to extend its functionality as needed.
type mdlModelsDao struct {
	*internal.MdlModelsDao
}

var (
	// MdlModels is a globally accessible object for table mdl_models operations.
	MdlModels = mdlModelsDao{internal.NewMdlModelsDao()}
)

// Add your custom methods and functionality below.
