// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlModelGroupItemsDao is the data access object for the table mdl_model_group_items.
// You can define custom methods on it to extend its functionality as needed.
type mdlModelGroupItemsDao struct {
	*internal.MdlModelGroupItemsDao
}

var (
	// MdlModelGroupItems is a globally accessible object for table mdl_model_group_items operations.
	MdlModelGroupItems = mdlModelGroupItemsDao{internal.NewMdlModelGroupItemsDao()}
)

// Add your custom methods and functionality below.
