// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlGroupModelsDao is the data access object for the table mdl_group_models.
// You can define custom methods on it to extend its functionality as needed.
type mdlGroupModelsDao struct {
	*internal.MdlGroupModelsDao
}

var (
	// MdlGroupModels is a globally accessible object for table mdl_group_models operations.
	MdlGroupModels = mdlGroupModelsDao{internal.NewMdlGroupModelsDao()}
)

// Add your custom methods and functionality below.
