// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlTenantModelsDao is the data access object for the table mdl_tenant_models.
// You can define custom methods on it to extend its functionality as needed.
type mdlTenantModelsDao struct {
	*internal.MdlTenantModelsDao
}

var (
	// MdlTenantModels is a globally accessible object for table mdl_tenant_models operations.
	MdlTenantModels = mdlTenantModelsDao{internal.NewMdlTenantModelsDao()}
)

// Add your custom methods and functionality below.
