// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlTenantGroupsDao is the data access object for the table mdl_tenant_groups.
// You can define custom methods on it to extend its functionality as needed.
type mdlTenantGroupsDao struct {
	*internal.MdlTenantGroupsDao
}

var (
	// MdlTenantGroups is a globally accessible object for table mdl_tenant_groups operations.
	MdlTenantGroups = mdlTenantGroupsDao{internal.NewMdlTenantGroupsDao()}
)

// Add your custom methods and functionality below.
