// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlPricingDao is the data access object for the table mdl_pricing.
// You can define custom methods on it to extend its functionality as needed.
type mdlPricingDao struct {
	*internal.MdlPricingDao
}

var (
	// MdlPricing is a globally accessible object for table mdl_pricing operations.
	MdlPricing = mdlPricingDao{internal.NewMdlPricingDao()}
)

// Add your custom methods and functionality below.
