// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// mdlModelGroupsDao is the data access object for the table mdl_model_groups.
// You can define custom methods on it to extend its functionality as needed.
type mdlModelGroupsDao struct {
	*internal.MdlModelGroupsDao
}

var (
	// MdlModelGroups is a globally accessible object for table mdl_model_groups operations.
	MdlModelGroups = mdlModelGroupsDao{internal.NewMdlModelGroupsDao()}
)

// Add your custom methods and functionality below.
