// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ntfTemplatesDao is the data access object for the table ntf_templates.
// You can define custom methods on it to extend its functionality as needed.
type ntfTemplatesDao struct {
	*internal.NtfTemplatesDao
}

var (
	// NtfTemplates is a globally accessible object for table ntf_templates operations.
	NtfTemplates = ntfTemplatesDao{internal.NewNtfTemplatesDao()}
)

// Add your custom methods and functionality below.
