// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ntfAnnouncementsDao is the data access object for the table ntf_announcements.
// You can define custom methods on it to extend its functionality as needed.
type ntfAnnouncementsDao struct {
	*internal.NtfAnnouncementsDao
}

var (
	// NtfAnnouncements is a globally accessible object for table ntf_announcements operations.
	NtfAnnouncements = ntfAnnouncementsDao{internal.NewNtfAnnouncementsDao()}
)

// Add your custom methods and functionality below.
