// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ntfReadStatusDao is the data access object for the table ntf_read_status.
// You can define custom methods on it to extend its functionality as needed.
type ntfReadStatusDao struct {
	*internal.NtfReadStatusDao
}

var (
	// NtfReadStatus is a globally accessible object for table ntf_read_status operations.
	NtfReadStatus = ntfReadStatusDao{internal.NewNtfReadStatusDao()}
)

// Add your custom methods and functionality below.
