// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ntfPreferencesDao is the data access object for the table ntf_preferences.
// You can define custom methods on it to extend its functionality as needed.
type ntfPreferencesDao struct {
	*internal.NtfPreferencesDao
}

var (
	// NtfPreferences is a globally accessible object for table ntf_preferences operations.
	NtfPreferences = ntfPreferencesDao{internal.NewNtfPreferencesDao()}
)

// Add your custom methods and functionality below.
