// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ntfSendLogDao is the data access object for the table ntf_send_log.
// You can define custom methods on it to extend its functionality as needed.
type ntfSendLogDao struct {
	*internal.NtfSendLogDao
}

var (
	// NtfSendLog is a globally accessible object for table ntf_send_log operations.
	NtfSendLog = ntfSendLogDao{internal.NewNtfSendLogDao()}
)

// Add your custom methods and functionality below.
