// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ntfMessagesDao is the data access object for the table ntf_messages.
// You can define custom methods on it to extend its functionality as needed.
type ntfMessagesDao struct {
	*internal.NtfMessagesDao
}

var (
	// NtfMessages is a globally accessible object for table ntf_messages operations.
	NtfMessages = ntfMessagesDao{internal.NewNtfMessagesDao()}
)

// Add your custom methods and functionality below.
