// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// opnWebhookConfigsDao is the data access object for the table opn_webhook_configs.
// You can define custom methods on it to extend its functionality as needed.
type opnWebhookConfigsDao struct {
	*internal.OpnWebhookConfigsDao
}

var (
	// OpnWebhookConfigs is a globally accessible object for table opn_webhook_configs operations.
	OpnWebhookConfigs = opnWebhookConfigsDao{internal.NewOpnWebhookConfigsDao()}
)

// Add your custom methods and functionality below.
