// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// opnWebhookDeliveryLogsDao is the data access object for the table opn_webhook_delivery_logs.
// You can define custom methods on it to extend its functionality as needed.
type opnWebhookDeliveryLogsDao struct {
	*internal.OpnWebhookDeliveryLogsDao
}

var (
	// OpnWebhookDeliveryLogs is a globally accessible object for table opn_webhook_delivery_logs operations.
	OpnWebhookDeliveryLogs = opnWebhookDeliveryLogsDao{internal.NewOpnWebhookDeliveryLogsDao()}
)

// Add your custom methods and functionality below.
