// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// opnWebhookEventsDao is the data access object for the table opn_webhook_events.
// You can define custom methods on it to extend its functionality as needed.
type opnWebhookEventsDao struct {
	*internal.OpnWebhookEventsDao
}

var (
	// OpnWebhookEvents is a globally accessible object for table opn_webhook_events operations.
	OpnWebhookEvents = opnWebhookEventsDao{internal.NewOpnWebhookEventsDao()}
)

// Add your custom methods and functionality below.
