// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// internalOpnAppsDao is an internal type for wrapping the internal DAO implementation.
type internalOpnAppsDao = *internal.OpnAppsDao

// opnAppsDao is the data access object for the table opn_apps.
// You can define custom methods on it to extend its functionality as needed.
type opnAppsDao struct {
	internalOpnAppsDao
}

var (
	// OpnApps is a globally accessible object for table opn_apps operations.
	OpnApps = opnAppsDao{
		internal.NewOpnAppsDao(),
	}
)

// Add your custom methods and functionality below.
