// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// opsSystemMetricsDao is the data access object for the table ops_system_metrics.
// You can define custom methods on it to extend its functionality as needed.
type opsSystemMetricsDao struct {
	*internal.OpsSystemMetricsDao
}

var (
	// OpsSystemMetrics is a globally accessible object for table ops_system_metrics operations.
	OpsSystemMetrics = opsSystemMetricsDao{internal.NewOpsSystemMetricsDao()}
)

// Add your custom methods and functionality below.
