// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// opsAlertEventsDao is the data access object for the table ops_alert_events.
// You can define custom methods on it to extend its functionality as needed.
type opsAlertEventsDao struct {
	*internal.OpsAlertEventsDao
}

var (
	// OpsAlertEvents is a globally accessible object for table ops_alert_events operations.
	OpsAlertEvents = opsAlertEventsDao{internal.NewOpsAlertEventsDao()}
)

// Add your custom methods and functionality below.
