// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// opsAlertRulesDao is the data access object for the table ops_alert_rules.
// You can define custom methods on it to extend its functionality as needed.
type opsAlertRulesDao struct {
	*internal.OpsAlertRulesDao
}

var (
	// OpsAlertRules is a globally accessible object for table ops_alert_rules operations.
	OpsAlertRules = opsAlertRulesDao{internal.NewOpsAlertRulesDao()}
)

// Add your custom methods and functionality below.
