// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordRedemptionsDao is the data access object for the table ord_redemptions.
// You can define custom methods on it to extend its functionality as needed.
type ordRedemptionsDao struct {
	*internal.OrdRedemptionsDao
}

var (
	// OrdRedemptions is a globally accessible object for table ord_redemptions operations.
	OrdRedemptions = ordRedemptionsDao{internal.NewOrdRedemptionsDao()}
)

// Add your custom methods and functionality below.
