// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordPromoCodesDao is the data access object for the table ord_promo_codes.
// You can define custom methods on it to extend its functionality as needed.
type ordPromoCodesDao struct {
	*internal.OrdPromoCodesDao
}

var (
	// OrdPromoCodes is a globally accessible object for table ord_promo_codes operations.
	OrdPromoCodes = ordPromoCodesDao{internal.NewOrdPromoCodesDao()}
)

// Add your custom methods and functionality below.
