// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordPaymentChannelsDao is the data access object for the table ord_payment_channels.
// You can define custom methods on it to extend its functionality as needed.
type ordPaymentChannelsDao struct {
	*internal.OrdPaymentChannelsDao
}

var (
	// OrdPaymentChannels is a globally accessible object for table ord_payment_channels operations.
	OrdPaymentChannels = ordPaymentChannelsDao{internal.NewOrdPaymentChannelsDao()}
)

// Add your custom methods and functionality below.
