// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordRedemptionUsagesDao is the data access object for the table ord_redemption_usages.
// You can define custom methods on it to extend its functionality as needed.
type ordRedemptionUsagesDao struct {
	*internal.OrdRedemptionUsagesDao
}

var (
	// OrdRedemptionUsages is a globally accessible object for table ord_redemption_usages operations.
	OrdRedemptionUsages = ordRedemptionUsagesDao{internal.NewOrdRedemptionUsagesDao()}
)

// Add your custom methods and functionality below.
