// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordRefundsDao is the data access object for the table ord_refunds.
// You can define custom methods on it to extend its functionality as needed.
type ordRefundsDao struct {
	*internal.OrdRefundsDao
}

var (
	// OrdRefunds is a globally accessible object for table ord_refunds operations.
	OrdRefunds = ordRefundsDao{internal.NewOrdRefundsDao()}
)

// Add your custom methods and functionality below.
