// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordOrdersDao is the data access object for the table ord_orders.
// You can define custom methods on it to extend its functionality as needed.
type ordOrdersDao struct {
	*internal.OrdOrdersDao
}

var (
	// OrdOrders is a globally accessible object for table ord_orders operations.
	OrdOrders = ordOrdersDao{internal.NewOrdOrdersDao()}
)

// Add your custom methods and functionality below.
