// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// ordPromoCodeUsagesDao is the data access object for the table ord_promo_code_usages.
// You can define custom methods on it to extend its functionality as needed.
type ordPromoCodeUsagesDao struct {
	*internal.OrdPromoCodeUsagesDao
}

var (
	// OrdPromoCodeUsages is a globally accessible object for table ord_promo_code_usages operations.
	OrdPromoCodeUsages = ordPromoCodeUsagesDao{internal.NewOrdPromoCodeUsagesDao()}
)

// Add your custom methods and functionality below.
