// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// plgExampleLogsDao is the data access object for the table plg_example_logs.
// You can define custom methods on it to extend its functionality as needed.
type plgExampleLogsDao struct {
	*internal.PlgExampleLogsDao
}

var (
	// PlgExampleLogs is a globally accessible object for table plg_example_logs operations.
	PlgExampleLogs = plgExampleLogsDao{internal.NewPlgExampleLogsDao()}
)

// Add your custom methods and functionality below.
