// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// plnTenantPlansDao is the data access object for the table pln_tenant_plans.
// You can define custom methods on it to extend its functionality as needed.
type plnTenantPlansDao struct {
	*internal.PlnTenantPlansDao
}

var (
	// PlnTenantPlans is a globally accessible object for table pln_tenant_plans operations.
	PlnTenantPlans = plnTenantPlansDao{internal.NewPlnTenantPlansDao()}
)

// Add your custom methods and functionality below.
