// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// plnFeatureFlagsDao is the data access object for the table pln_feature_flags.
// You can define custom methods on it to extend its functionality as needed.
type plnFeatureFlagsDao struct {
	*internal.PlnFeatureFlagsDao
}

var (
	// PlnFeatureFlags is a globally accessible object for table pln_feature_flags operations.
	PlnFeatureFlags = plnFeatureFlagsDao{internal.NewPlnFeatureFlagsDao()}
)

// Add your custom methods and functionality below.
