// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// plnPlansDao is the data access object for the table pln_plans.
// You can define custom methods on it to extend its functionality as needed.
type plnPlansDao struct {
	*internal.PlnPlansDao
}

var (
	// PlnPlans is a globally accessible object for table pln_plans operations.
	PlnPlans = plnPlansDao{internal.NewPlnPlansDao()}
)

// Add your custom methods and functionality below.
