// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sptFeedbacksDao is the data access object for the table spt_feedbacks.
// You can define custom methods on it to extend its functionality as needed.
type sptFeedbacksDao struct {
	*internal.SptFeedbacksDao
}

var (
	// SptFeedbacks is a globally accessible object for table spt_feedbacks operations.
	SptFeedbacks = sptFeedbacksDao{internal.NewSptFeedbacksDao()}
)

// Add your custom methods and functionality below.
