// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sptAttachmentsDao is the data access object for the table spt_attachments.
// You can define custom methods on it to extend its functionality as needed.
type sptAttachmentsDao struct {
	*internal.SptAttachmentsDao
}

var (
	// SptAttachments is a globally accessible object for table spt_attachments operations.
	SptAttachments = sptAttachmentsDao{internal.NewSptAttachmentsDao()}
)

// Add your custom methods and functionality below.
