// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sptTicketsDao is the data access object for the table spt_tickets.
// You can define custom methods on it to extend its functionality as needed.
type sptTicketsDao struct {
	*internal.SptTicketsDao
}

var (
	// SptTickets is a globally accessible object for table spt_tickets operations.
	SptTickets = sptTicketsDao{internal.NewSptTicketsDao()}
)

// Add your custom methods and functionality below.
