// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sptCategoriesDao is the data access object for the table spt_categories.
// You can define custom methods on it to extend its functionality as needed.
type sptCategoriesDao struct {
	*internal.SptCategoriesDao
}

var (
	// SptCategories is a globally accessible object for table spt_categories operations.
	SptCategories = sptCategoriesDao{internal.NewSptCategoriesDao()}
)

// Add your custom methods and functionality below.
