// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sptArticlesDao is the data access object for the table spt_articles.
// You can define custom methods on it to extend its functionality as needed.
type sptArticlesDao struct {
	*internal.SptArticlesDao
}

var (
	// SptArticles is a globally accessible object for table spt_articles operations.
	SptArticles = sptArticlesDao{internal.NewSptArticlesDao()}
)

// Add your custom methods and functionality below.
