// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sptRepliesDao is the data access object for the table spt_replies.
// You can define custom methods on it to extend its functionality as needed.
type sptRepliesDao struct {
	*internal.SptRepliesDao
}

var (
	// SptReplies is a globally accessible object for table spt_replies operations.
	SptReplies = sptRepliesDao{internal.NewSptRepliesDao()}
)

// Add your custom methods and functionality below.
