// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAgreementsDao is the data access object for the table sys_agreements.
type sysAgreementsDao struct {
	*internal.SysAgreementsDao
}

var (
	// SysAgreements is a globally accessible object for table sys_agreements operations.
	SysAgreements = sysAgreementsDao{internal.NewSysAgreementsDao()}
)
