// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAgreementAcceptancesDao is the data access object for the table sys_agreement_acceptances.
type sysAgreementAcceptancesDao struct {
	*internal.SysAgreementAcceptancesDao
}

var (
	// SysAgreementAcceptances is a globally accessible object for table sys_agreement_acceptances operations.
	SysAgreementAcceptances = sysAgreementAcceptancesDao{internal.NewSysAgreementAcceptancesDao()}
)
