// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysIdempotencyRecordsDao is the data access object for the table sys_idempotency_records.
// You can define custom methods on it to extend its functionality as needed.
type sysIdempotencyRecordsDao struct {
	*internal.SysIdempotencyRecordsDao
}

var (
	// SysIdempotencyRecords is a globally accessible object for table sys_idempotency_records operations.
	SysIdempotencyRecords = sysIdempotencyRecordsDao{internal.NewSysIdempotencyRecordsDao()}
)

// Add your custom methods and functionality below.
