// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysEmailVerifyCodesDao is the data access object for the table sys_email_verify_codes.
// You can define custom methods on it to extend its functionality as needed.
type sysEmailVerifyCodesDao struct {
	*internal.SysEmailVerifyCodesDao
}

var (
	// SysEmailVerifyCodes is a globally accessible object for table sys_email_verify_codes operations.
	SysEmailVerifyCodes = sysEmailVerifyCodesDao{internal.NewSysEmailVerifyCodesDao()}
)

// Add your custom methods and functionality below.
