// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAdminDataScopesDao is the data access object for the table sys_admin_data_scopes.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminDataScopesDao struct {
	*internal.SysAdminDataScopesDao
}

var (
	// SysAdminDataScopes is a globally accessible object for table sys_admin_data_scopes operations.
	SysAdminDataScopes = sysAdminDataScopesDao{internal.NewSysAdminDataScopesDao()}
)

// Add your custom methods and functionality below.
