// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysCronJobsDao is the data access object for the table sys_cron_jobs.
// You can define custom methods on it to extend its functionality as needed.
type sysCronJobsDao struct {
	*internal.SysCronJobsDao
}

var (
	// SysCronJobs is a globally accessible object for table sys_cron_jobs operations.
	SysCronJobs = sysCronJobsDao{internal.NewSysCronJobsDao()}
)

// Add your custom methods and functionality below.
