// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysErrorLogsDao is the data access object for the table sys_error_logs.
// You can define custom methods on it to extend its functionality as needed.
type sysErrorLogsDao struct {
	*internal.SysErrorLogsDao
}

var (
	// SysErrorLogs is a globally accessible object for table sys_error_logs operations.
	SysErrorLogs = sysErrorLogsDao{internal.NewSysErrorLogsDao()}
)

// Add your custom methods and functionality below.
