// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAdminRolePermissionsDao is the data access object for the table sys_admin_role_permissions.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminRolePermissionsDao struct {
	*internal.SysAdminRolePermissionsDao
}

var (
	// SysAdminRolePermissions is a globally accessible object for table sys_admin_role_permissions operations.
	SysAdminRolePermissions = sysAdminRolePermissionsDao{internal.NewSysAdminRolePermissionsDao()}
)

// Add your custom methods and functionality below.
