// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysOptionsDao is the data access object for the table sys_options.
// You can define custom methods on it to extend its functionality as needed.
type sysOptionsDao struct {
	*internal.SysOptionsDao
}

var (
	// SysOptions is a globally accessible object for table sys_options operations.
	SysOptions = sysOptionsDao{internal.NewSysOptionsDao()}
)

// Add your custom methods and functionality below.
