// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAdminUsersDao is the data access object for the table sys_admin_users.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminUsersDao struct {
	*internal.SysAdminUsersDao
}

var (
	// SysAdminUsers is a globally accessible object for table sys_admin_users operations.
	SysAdminUsers = sysAdminUsersDao{internal.NewSysAdminUsersDao()}
)

// Add your custom methods and functionality below.
