// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysPluginsDao is the data access object for the table sys_plugins.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginsDao struct {
	*internal.SysPluginsDao
}

var (
	// SysPlugins is a globally accessible object for table sys_plugins operations.
	SysPlugins = sysPluginsDao{internal.NewSysPluginsDao()}
)

// Add your custom methods and functionality below.
