// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAdminRolesDao is the data access object for the table sys_admin_roles.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminRolesDao struct {
	*internal.SysAdminRolesDao
}

var (
	// SysAdminRoles is a globally accessible object for table sys_admin_roles operations.
	SysAdminRoles = sysAdminRolesDao{internal.NewSysAdminRolesDao()}
)

// Add your custom methods and functionality below.
