// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysSessionsDao is the data access object for the table sys_sessions.
// You can define custom methods on it to extend its functionality as needed.
type sysSessionsDao struct {
	*internal.SysSessionsDao
}

var (
	// SysSessions is a globally accessible object for table sys_sessions operations.
	SysSessions = sysSessionsDao{internal.NewSysSessionsDao()}
)

// Add your custom methods and functionality below.
