// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysCronJobExecutionsDao is the data access object for the table sys_cron_job_executions.
// You can define custom methods on it to extend its functionality as needed.
type sysCronJobExecutionsDao struct {
	*internal.SysCronJobExecutionsDao
}

var (
	// SysCronJobExecutions is a globally accessible object for table sys_cron_job_executions operations.
	SysCronJobExecutions = sysCronJobExecutionsDao{internal.NewSysCronJobExecutionsDao()}
)

// Add your custom methods and functionality below.
