// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAdminRolePermsDao is the data access object for the table sys_admin_role_perms.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminRolePermsDao struct {
	*internal.SysAdminRolePermsDao
}

var (
	// SysAdminRolePerms is a globally accessible object for table sys_admin_role_perms operations.
	SysAdminRolePerms = sysAdminRolePermsDao{internal.NewSysAdminRolePermsDao()}
)

// Add your custom methods and functionality below.
