// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// sysAdminUserRolesDao is the data access object for the table sys_admin_user_roles.
// You can define custom methods on it to extend its functionality as needed.
type sysAdminUserRolesDao struct {
	*internal.SysAdminUserRolesDao
}

var (
	// SysAdminUserRoles is a globally accessible object for table sys_admin_user_roles operations.
	SysAdminUserRoles = sysAdminUserRolesDao{internal.NewSysAdminUserRolesDao()}
)

// Add your custom methods and functionality below.
