// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntMemberModelScopesDao is the data access object for the table tnt_member_model_scopes.
// You can define custom methods on it to extend its functionality as needed.
type tntMemberModelScopesDao struct {
	*internal.TntMemberModelScopesDao
}

var (
	// TntMemberModelScopes is a globally accessible object for table tnt_member_model_scopes operations.
	TntMemberModelScopes = tntMemberModelScopesDao{internal.NewTntMemberModelScopesDao()}
)

// Add your custom methods and functionality below.
