// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntUsersDao is the data access object for the table tnt_users.
// You can define custom methods on it to extend its functionality as needed.
type tntUsersDao struct {
	*internal.TntUsersDao
}

var (
	// TntUsers is a globally accessible object for table tnt_users operations.
	TntUsers = tntUsersDao{internal.NewTntUsersDao()}
)

// Add your custom methods and functionality below.
