// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntTenantsDao is the data access object for the table tnt_tenants.
// You can define custom methods on it to extend its functionality as needed.
type tntTenantsDao struct {
	*internal.TntTenantsDao
}

var (
	// TntTenants is a globally accessible object for table tnt_tenants operations.
	TntTenants = tntTenantsDao{internal.NewTntTenantsDao()}
)

// Add your custom methods and functionality below.
