// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntTenantLevelConfigsDao is the data access object for the table tnt_tenant_level_configs.
// You can define custom methods on it to extend its functionality as needed.
type tntTenantLevelConfigsDao struct {
	*internal.TntTenantLevelConfigsDao
}

var (
	// TntTenantLevelConfigs is a globally accessible object for table tnt_tenant_level_configs operations.
	TntTenantLevelConfigs = tntTenantLevelConfigsDao{internal.NewTntTenantLevelConfigsDao()}
)

// Add your custom methods and functionality below.
