// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntInvitationsDao is the data access object for the table tnt_invitations.
// You can define custom methods on it to extend its functionality as needed.
type tntInvitationsDao struct {
	*internal.TntInvitationsDao
}

var (
	// TntInvitations is a globally accessible object for table tnt_invitations operations.
	TntInvitations = tntInvitationsDao{internal.NewTntInvitationsDao()}
)

// Add your custom methods and functionality below.
