// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntProjectsDao is the data access object for the table tnt_projects.
// You can define custom methods on it to extend its functionality as needed.
type tntProjectsDao struct {
	*internal.TntProjectsDao
}

var (
	// TntProjects is a globally accessible object for table tnt_projects operations.
	TntProjects = tntProjectsDao{internal.NewTntProjectsDao()}
)

// Add your custom methods and functionality below.
