// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntOauthIdentitiesDao is the data access object for the table tnt_oauth_identities.
// You can define custom methods on it to extend its functionality as needed.
type tntOauthIdentitiesDao struct {
	*internal.TntOauthIdentitiesDao
}

var (
	// TntOauthIdentities is a globally accessible object for table tnt_oauth_identities operations.
	TntOauthIdentities = tntOauthIdentitiesDao{internal.NewTntOauthIdentitiesDao()}
)

// Add your custom methods and functionality below.
