// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntMemberImportsDao is the data access object for the table tnt_member_imports.
// You can define custom methods on it to extend its functionality as needed.
type tntMemberImportsDao struct {
	*internal.TntMemberImportsDao
}

var (
	// TntMemberImports is a globally accessible object for table tnt_member_imports operations.
	TntMemberImports = tntMemberImportsDao{internal.NewTntMemberImportsDao()}
)

// Add your custom methods and functionality below.
