// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tntTenantPluginsDao is the data access object for the table tnt_tenant_plugins.
// You can define custom methods on it to extend its functionality as needed.
type tntTenantPluginsDao struct {
	*internal.TntTenantPluginsDao
}

var (
	// TntTenantPlugins is a globally accessible object for table tnt_tenant_plugins operations.
	TntTenantPlugins = tntTenantPluginsDao{internal.NewTntTenantPluginsDao()}
)

// Add your custom methods and functionality below.
