// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tskModelTasksDao is the data access object for the table tsk_model_tasks.
// You can define custom methods on it to extend its functionality as needed.
type tskModelTasksDao struct {
	*internal.TskModelTasksDao
}

var (
	// TskModelTasks is a globally accessible object for table tsk_model_tasks operations.
	TskModelTasks = tskModelTasksDao{internal.NewTskModelTasksDao()}
)

// Add your custom methods and functionality below.
