// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tskTaskLogsDao is the data access object for the table tsk_task_logs.
// You can define custom methods on it to extend its functionality as needed.
type tskTaskLogsDao struct {
	*internal.TskTaskLogsDao
}

var (
	// TskTaskLogs is a globally accessible object for table tsk_task_logs operations.
	TskTaskLogs = tskTaskLogsDao{internal.NewTskTaskLogsDao()}
)

// Add your custom methods and functionality below.
