// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// tskTasksDao is the data access object for the table tsk_tasks.
// You can define custom methods on it to extend its functionality as needed.
type tskTasksDao struct {
	*internal.TskTasksDao
}

var (
	// TskTasks is a globally accessible object for table tsk_tasks operations.
	TskTasks = tskTasksDao{internal.NewTskTasksDao()}
)

// Add your custom methods and functionality below.
