// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/qianfree/team-api/internal/dao/internal"
)

// internalTskAsyncTasksDao is an internal type for wrapping the internal DAO implementation.
type internalTskAsyncTasksDao = *internal.TskAsyncTasksDao

// tskAsyncTasksDao is the data access object for the table tsk_async_tasks.
// You can define custom methods on it to extend its functionality as needed.
type tskAsyncTasksDao struct {
	internalTskAsyncTasksDao
}

var (
	// TskAsyncTasks is a globally accessible object for table tsk_async_tasks operations.
	TskAsyncTasks = tskAsyncTasksDao{
		internal.NewTskAsyncTasksDao(),
	}
)

// Add your custom methods and functionality below.
