// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ChnDebugLogs is the golang structure for table chn_debug_logs.
type ChnDebugLogs struct {
	Id                   int64       `json:"id"                     orm:"id"                     description:"主键ID"`                                                                                                                                    // 主键ID
	ChannelId            int64       `json:"channel_id"             orm:"channel_id"             description:"渠道ID（逻辑关联 chn_channels.id，无外键）"`                                                                                                          // 渠道ID（逻辑关联 chn_channels.id，无外键）
	ChannelName          string      `json:"channel_name"           orm:"channel_name"           description:"渠道名称（冗余存储，渠道删除后仍可辨识）"`                                                                                                                    // 渠道名称（冗余存储，渠道删除后仍可辨识）
	ChannelType          int         `json:"channel_type"           orm:"channel_type"           description:"渠道类型（ProviderType 枚举值）"`                                                                                                                  // 渠道类型（ProviderType 枚举值）
	RequestId            string      `json:"request_id"             orm:"request_id"             description:"请求唯一ID（同一请求多次重试共享）"`                                                                                                                      // 请求唯一ID（同一请求多次重试共享）
	TenantId             int64       `json:"tenant_id"              orm:"tenant_id"              description:"租户ID"`                                                                                                                                    // 租户ID
	UserId               int64       `json:"user_id"                orm:"user_id"                description:"用户ID"`                                                                                                                                    // 用户ID
	ApiKeyId             int64       `json:"api_key_id"             orm:"api_key_id"             description:"API Key ID"`                                                                                                                              // API Key ID
	ModelName            string      `json:"model_name"             orm:"model_name"             description:"用户请求的模型名"`                                                                                                                                // 用户请求的模型名
	UpstreamModel        string      `json:"upstream_model"         orm:"upstream_model"         description:"上游实际使用的模型名（模型映射后）"`                                                                                                                       // 上游实际使用的模型名（模型映射后）
	RelayMode            string      `json:"relay_mode"             orm:"relay_mode"             description:"转发模式（chat_completions/claude_messages/embeddings 等）"`                                                                                     // 转发模式（chat_completions/claude_messages/embeddings 等）
	InboundPath          string      `json:"inbound_path"           orm:"inbound_path"           description:"入站端点路径（如 /v1/chat/completions）"`                                                                                                          // 入站端点路径（如 /v1/chat/completions）
	UpstreamUrl          string      `json:"upstream_url"           orm:"upstream_url"           description:"上游请求 URL（query 中的凭证参数已脱敏）"`                                                                                                               // 上游请求 URL（query 中的凭证参数已脱敏）
	IsStream             bool        `json:"is_stream"              orm:"is_stream"              description:"是否流式请求"`                                                                                                                                  // 是否流式请求
	RetryIndex           int         `json:"retry_index"            orm:"retry_index"            description:"重试轮次（0=首次尝试）"`                                                                                                                            // 重试轮次（0=首次尝试）
	IsFinal              bool        `json:"is_final"               orm:"is_final"               description:"是否为产生客户端响应的最终尝试（成功/终止/流中断）"`                                                                                                              // 是否为产生客户端响应的最终尝试（成功/终止/流中断）
	UpstreamStatusCode   int         `json:"upstream_status_code"   orm:"upstream_status_code"   description:"上游 HTTP 状态码（未发起请求或连接失败为 NULL）"`                                                                                                           // 上游 HTTP 状态码（未发起请求或连接失败为 NULL）
	ClientStatusCode     int         `json:"client_status_code"     orm:"client_status_code"     description:"返回客户端的状态码"`                                                                                                                               // 返回客户端的状态码
	Error                string      `json:"error"                  orm:"error"                  description:"本尝试的错误信息（成功为空）"`                                                                                                                          // 本尝试的错误信息（成功为空）
	ClientReqHeaders     string      `json:"client_req_headers"     orm:"client_req_headers"     description:"段1 客户端请求头（凭证类头脱敏：前6后4）JSON"`                                                                                                              // 段1 客户端请求头（凭证类头脱敏：前6后4）JSON
	ClientReqBody        string      `json:"client_req_body"        orm:"client_req_body"        description:"段1 客户端请求体（完整不截断；二进制为 base64，见 encoding 列）"`                                                                                               // 段1 客户端请求体（完整不截断；二进制为 base64，见 encoding 列）
	ClientReqEncoding    string      `json:"client_req_encoding"    orm:"client_req_encoding"    description:"段1 编码：plain / base64"`                                                                                                                    // 段1 编码：plain / base64
	UpstreamReqHeaders   string      `json:"upstream_req_headers"   orm:"upstream_req_headers"   description:"段2 发往上游的最终请求头（协议转换+override 后，凭证类脱敏）JSON"`                                                                                                // 段2 发往上游的最终请求头（协议转换+override 后，凭证类脱敏）JSON
	UpstreamReqBody      string      `json:"upstream_req_body"      orm:"upstream_req_body"      description:"段2 发往上游的请求体（实际发送字节，含协议转换；二进制为 base64）"`                                                                                                   // 段2 发往上游的请求体（实际发送字节，含协议转换；二进制为 base64）
	UpstreamReqEncoding  string      `json:"upstream_req_encoding"  orm:"upstream_req_encoding"  description:"段2 编码：plain / base64"`                                                                                                                    // 段2 编码：plain / base64
	UpstreamRespHeaders  string      `json:"upstream_resp_headers"  orm:"upstream_resp_headers"  description:"段3 上游响应头 JSON（Content-Encoding 可能已被 net/http 透明解压移除）"`                                                                                    // 段3 上游响应头 JSON（Content-Encoding 可能已被 net/http 透明解压移除）
	UpstreamRespBody     string      `json:"upstream_resp_body"     orm:"upstream_resp_body"     description:"段3 上游响应体（Go 透明解压后的字节；流式为 SSE 原文；二进制为 base64）"`                                                                                            // 段3 上游响应体（Go 透明解压后的字节；流式为 SSE 原文；二进制为 base64）
	UpstreamRespEncoding string      `json:"upstream_resp_encoding" orm:"upstream_resp_encoding" description:"段3 编码：plain / base64"`                                                                                                                    // 段3 编码：plain / base64
	ClientRespHeaders    string      `json:"client_resp_headers"    orm:"client_resp_headers"    description:"段4 返回客户端的响应头 JSON"`                                                                                                                       // 段4 返回客户端的响应头 JSON
	ClientRespBody       string      `json:"client_resp_body"       orm:"client_resp_body"       description:"段4 返回客户端的响应体（协议转换后，完整不截断；二进制为 base64）"`                                                                                                   // 段4 返回客户端的响应体（协议转换后，完整不截断；二进制为 base64）
	ClientRespEncoding   string      `json:"client_resp_encoding"   orm:"client_resp_encoding"   description:"段4 编码：plain / base64"`                                                                                                                    // 段4 编码：plain / base64
	UpstreamLatencyMs    int         `json:"upstream_latency_ms"    orm:"upstream_latency_ms"    description:"上游往返耗时（RoundTrip 到响应头）毫秒"`                                                                                                                // 上游往返耗时（RoundTrip 到响应头）毫秒
	TotalLatencyMs       int         `json:"total_latency_ms"       orm:"total_latency_ms"       description:"请求总耗时毫秒"`                                                                                                                                 // 请求总耗时毫秒
	FirstTokenMs         int         `json:"first_token_ms"         orm:"first_token_ms"         description:"首字节延迟毫秒"`                                                                                                                                 // 首字节延迟毫秒
	ClientReqBytes       int64       `json:"client_req_bytes"       orm:"client_req_bytes"       description:"段1 请求体原始字节数（base64 落库膨胀前的真实大小）"`                                                                                                          // 段1 请求体原始字节数（base64 落库膨胀前的真实大小）
	UpstreamReqBytes     int64       `json:"upstream_req_bytes"     orm:"upstream_req_bytes"     description:"段2 请求体原始字节数"`                                                                                                                             // 段2 请求体原始字节数
	UpstreamRespBytes    int64       `json:"upstream_resp_bytes"    orm:"upstream_resp_bytes"    description:"段3 响应体原始字节数"`                                                                                                                             // 段3 响应体原始字节数
	ClientRespBytes      int64       `json:"client_resp_bytes"      orm:"client_resp_bytes"      description:"段4 响应体原始字节数"`                                                                                                                             // 段4 响应体原始字节数
	CreatedAt            *gtime.Time `json:"created_at"             orm:"created_at"             description:"创建时间"`                                                                                                                                    // 创建时间
	Conversion           string      `json:"conversion"             orm:"conversion"             description:"协议转换信息 JSON：client_format 客户端协议 / upstream_format 上游协议 / chain 请求侧转换链 / bridge 桥接方式（responses_api|responses_direct|pass_through，空=常规转换）"` // 协议转换信息 JSON：client_format 客户端协议 / upstream_format 上游协议 / chain 请求侧转换链 / bridge 桥接方式（responses_api|responses_direct|pass_through，空=常规转换）
}
