// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MdlPricing is the golang structure for table mdl_pricing.
type MdlPricing struct {
	Id              int64       `json:"id"                orm:"id"                description:""`                                                                                                                                                                                                                                                                                                                        //
	ModelId         int64       `json:"model_id"          orm:"model_id"          description:"关联模型ID"`                                                                                                                                                                                                                                                                                                                  // 关联模型ID
	BillingMode     string      `json:"billing_mode"      orm:"billing_mode"      description:"计费模式：token（按量）/ per_request（按次）/ tiered（阶梯按量）"`                                                                                                                                                                                                                                                                           // 计费模式：token（按量）/ per_request（按次）/ tiered（阶梯按量）
	CreatedAt       *gtime.Time `json:"created_at"        orm:"created_at"        description:""`                                                                                                                                                                                                                                                                                                                        //
	UpdatedAt       *gtime.Time `json:"updated_at"        orm:"updated_at"        description:""`                                                                                                                                                                                                                                                                                                                        //
	PriceNote       string      `json:"price_note"        orm:"price_note"        description:"价格说明（仅管理后台可见，调价背景等内部备注），仅 min_tokens=0 锚点行使用，NULL=无"`                                                                                                                                                                                                                                                                     // 价格说明（仅管理后台可见，调价背景等内部备注），仅 min_tokens=0 锚点行使用，NULL=无
	DiscountLabel   string      `json:"discount_label"    orm:"discount_label"    description:"折扣标签（对外展示，如\"7折起\"、\"限时5折\"），仅 min_tokens=0 锚点行使用，NULL/空=不展示"`                                                                                                                                                                                                                                                            // 折扣标签（对外展示，如"7折起"、"限时5折"），仅 min_tokens=0 锚点行使用，NULL/空=不展示
	PriceChangeNote string      `json:"price_change_note" orm:"price_change_note" description:"价格调整说明（对外展示，提示用户价格有变动，如\"9月1日起输入价下调\"），仅 min_tokens=0 锚点行使用，NULL/空=不展示"`                                                                                                                                                                                                                                                  // 价格调整说明（对外展示，提示用户价格有变动，如"9月1日起输入价下调"），仅 min_tokens=0 锚点行使用，NULL/空=不展示
	Pricing         string      `json:"pricing"           orm:"pricing"           description:"计费详情（JSONB，按 billing_mode 单模式存储）：token={input_price,output_price,cache_read_price,cache_creation_price}；tiered={tiers:[{min_tokens,max_tokens,input_price,output_price}],cache_read_price,cache_creation_price}；per_request={price}；per_second={unit:\"second\",prices:{分辨率规格:每秒单价,\"*\":兜底价}}；顶层可含 time_segments（时段定价）"` // 计费详情（JSONB，按 billing_mode 单模式存储）：token={input_price,output_price,cache_read_price,cache_creation_price}；tiered={tiers:[{min_tokens,max_tokens,input_price,output_price}],cache_read_price,cache_creation_price}；per_request={price}；per_second={unit:"second",prices:{分辨率规格:每秒单价,"*":兜底价}}；顶层可含 time_segments（时段定价）
	OfficialPricing string      `json:"official_pricing"  orm:"official_pricing"  description:"官方参考定价 JSONB（结构与 pricing 一致 + billing_mode 键，本位币；仅作定价折扣计算基准与几折展示，非计费依据）"`                                                                                                                                                                                                                                                 // 官方参考定价 JSONB（结构与 pricing 一致 + billing_mode 键，本位币；仅作定价折扣计算基准与几折展示，非计费依据）
}
